[package]
name = "transaction_engine"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"]}
regex = "1.5"

[dev-dependencies]
rstest = "0.11.0"